/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Alias Property Sync Plugin for Obsidian v1.1
*/
"use strict";
var obsidian = require("obsidian");

var DEFAULT_SETTINGS = {
    headingsToTrack: "1-5",
    enableLogging: false,
    syncOnEnter: true,
    syncOnFileOpen: true,
    autoAliasLogArray: [] 
};

// --- AliasActionModal Class ---
var AliasActionModal = class extends obsidian.Modal {
    constructor(app, plugin) {
        super(app);
        this.plugin = plugin;
        this.selectedFolders = new Set();
    }

    onOpen() {
        // 1. Add Custom Class for Blur Effect
        this.containerEl.addClass("alias-sync-blur-modal");

        const { contentEl } = this;
        contentEl.empty(); 
        contentEl.createEl('h2', { text: 'Alias Property Sync Actions' });

        // --- 2. Auto-Sync Settings ---
        contentEl.createEl('h3', { text: 'Auto-Sync Settings' });
        const settingsContainer = contentEl.createDiv();
        settingsContainer.style.marginBottom = '24px';
        settingsContainer.style.padding = '10px';
        settingsContainer.style.border = '1px solid var(--background-modifier-border)';
        settingsContainer.style.borderRadius = '6px';

        new obsidian.Setting(settingsContainer)
            .setName("Sync on File Open")
            .setDesc("Update aliases automatically when opening a file.")
            .addToggle(toggle => toggle
                .setValue(this.plugin.settings.syncOnFileOpen)
                .onChange(async (value) => {
                    this.plugin.settings.syncOnFileOpen = value;
                    await this.plugin.saveSettings();
                }));

        new obsidian.Setting(settingsContainer)
            .setName("Sync on Enter")
            .setDesc("Update aliases when Enter is pressed.")
            .addToggle(toggle => toggle
                .setValue(this.plugin.settings.syncOnEnter)
                .onChange(async (value) => {
                    this.plugin.settings.syncOnEnter = value;
                    await this.plugin.saveSettings();
                }));

        // --- 3. Global Actions ---
        contentEl.createEl('h3', { text: 'Global Actions' });
        const globalContainer = contentEl.createDiv();
        globalContainer.style.display = 'flex';
        globalContainer.style.gap = '12px'; 
        globalContainer.style.marginBottom = '24px';

        const addHoverEffect = (btnComp) => {
            btnComp.buttonEl.style.cursor = 'pointer';
            btnComp.buttonEl.onmouseover = () => btnComp.buttonEl.style.opacity = '0.85';
            btnComp.buttonEl.onmouseout = () => btnComp.buttonEl.style.opacity = '1';
        };

        const syncAllBtn = new obsidian.ButtonComponent(globalContainer)
            .setButtonText("Sync All Files")
            .setCta()
            .onClick(async () => {
                this.close();
                await this.plugin.syncAllMarkdownFiles();
            });
        addHoverEffect(syncAllBtn);

        const removeAllBtn = new obsidian.ButtonComponent(globalContainer)
            .setButtonText("Remove All Plugin Aliases")
            .setWarning()
            .onClick(async () => {
                this.close();
                await this.plugin.removeAllAutoAliases();
            });
        addHoverEffect(removeAllBtn);

        // --- 4. Folder Selection ---
        contentEl.createEl('h3', { text: 'Sync Specific Folders' });
        contentEl.createEl('p', { 
            text: 'Select folders to sync. (Files in root are treated as "Root").', 
            cls: 'setting-item-description' 
        });

        const listContainer = contentEl.createDiv();
        listContainer.style.maxHeight = '300px';
        listContainer.style.overflowY = 'auto';
        listContainer.style.border = '1px solid var(--background-modifier-border)';
        listContainer.style.borderRadius = '6px';
        listContainer.style.padding = '10px';
        listContainer.style.marginBottom = '20px';
        listContainer.style.backgroundColor = 'var(--background-primary)';

        const folders = this.app.vault.getAllLoadedFiles()
            .filter(f => f instanceof obsidian.TFolder)
            .sort((a, b) => a.path.localeCompare(b.path));
        
        const rootFolder = this.app.vault.getRoot();
        if (!folders.some(f => f.path === rootFolder.path)) {
            folders.unshift(rootFolder);
        }

        folders.forEach(folder => {
            const itemDiv = listContainer.createDiv();
            itemDiv.style.display = 'flex';
            itemDiv.style.alignItems = 'center';
            itemDiv.style.padding = '6px 8px';
            itemDiv.style.cursor = 'pointer';
            itemDiv.style.borderRadius = '4px';
            
            itemDiv.onmouseover = () => {
                itemDiv.style.backgroundColor = 'var(--background-modifier-hover)';
            };
            itemDiv.onmouseout = () => {
                itemDiv.style.backgroundColor = 'transparent';
            };

            const checkbox = itemDiv.createEl('input', { type: 'checkbox' });
            checkbox.style.marginRight = '10px';
            checkbox.style.cursor = 'pointer';
            
            const label = itemDiv.createEl("span");
            const folderName = (folder.path === '/' || folder.path === '') ? '/ (Root)' : folder.path;
            label.setText(folderName);
            label.style.color = 'var(--text-normal)'; 
            label.style.fontSize = '14px';
            label.style.flex = '1'; 

            itemDiv.onclick = (e) => {
                if (e.target !== checkbox) {
                    checkbox.checked = !checkbox.checked;
                }
                if (checkbox.checked) {
                    this.selectedFolders.add(folder);
                } else {
                    this.selectedFolders.delete(folder);
                }
            };
        });

        const actionContainer = contentEl.createDiv();
        actionContainer.style.display = 'flex';
        actionContainer.style.justifyContent = 'flex-end';
        actionContainer.style.marginTop = '10px';

        const syncSelectedBtn = new obsidian.ButtonComponent(actionContainer)
            .setButtonText("Sync Selected Folders")
            .setCta()
            .onClick(async () => {
                if (this.selectedFolders.size === 0) {
                    new obsidian.Notice("No folders selected.");
                    return;
                }
                this.close();
                await this.plugin.syncSelectedFolders(Array.from(this.selectedFolders));
            });
        addHoverEffect(syncSelectedBtn);
    }

    onClose() {
        const { contentEl } = this;
        contentEl.empty();
    }
}
// --- End AliasActionModal Class ---

var AliasPropertyPlugin = class extends obsidian.Plugin {
    constructor() {
        super(...arguments);
        this.autoAliasLog = new Set(); 
    }
    
    log(message, ...args) {
        if (this.settings.enableLogging) {
            console.log(`[Alias Property Sync] ${message}`, ...args);
        }
    }
    
    async onload() {
        await this.loadSettings();
        this.log("Plugin loaded. Log size:", this.autoAliasLog.size);
        
        // --- 1. Inject Custom CSS for Blur ---
        this.addStyle();

        this.addCommand({
            id: "sync-alias-property",
            name: "Sync alias property from headings (Current File)",
            callback: () => this.syncCurrentFile()
        });
        
        this.addRibbonIcon("list-tree", "Alias Property Sync Actions", () => {
            new AliasActionModal(this.app, this).open();
        });

        this.registerEvent(
            this.app.workspace.on("file-menu", (menu, file) => {
                if (file instanceof obsidian.TFile && file.extension === 'md') {
                    menu.addItem((item) => {
                        item.setTitle("Sync Aliases from Headings")
                            .setIcon("list-tree")
                            .onClick(() => {
                                this.syncFile(file);
                                new obsidian.Notice(`Alias property synced for ${file.basename}!`);
                            });
                    });
                } 
                else if (file instanceof obsidian.TFolder) {
                     menu.addItem((item) => {
                        item.setTitle("Sync Aliases for Folder Contents")
                            .setIcon("list-tree")
                            .onClick(async () => {
                                await this.syncSelectedFolders([file]);
                            });
                    });
                }
            })
        );
        
        this.addSettingTab(new AliasSettingTab(this.app, this));
        
        this.registerEvent(
            this.app.workspace.on("file-open", (file) => {
                if (this.settings.syncOnFileOpen && file) {
                    this.syncFile(file);
                }
            })
        );
        
        this.registerDomEvent(document, 'keydown', (evt) => {
            if (!this.settings.syncOnEnter) return;
            if (evt.key === 'Enter' && !evt.shiftKey && !evt.ctrlKey && !evt.metaKey && !evt.altKey) {
                const file = this.app.workspace.getActiveFile();
                if (file) {
                    setTimeout(() => {
                        this.syncFile(file, true);
                    }, 100);
                }
            }
        });
    }

    onunload() {
        // Clean up the injected style
        const style = document.getElementById('alias-sync-plugin-styles');
        if (style) style.remove();
    }

    addStyle() {
        const styleId = 'alias-sync-plugin-styles';
        if (document.getElementById(styleId)) return;

        const style = document.createElement('style');
        style.id = styleId;
        style.textContent = `
            .alias-sync-blur-modal .modal-bg {
                backdrop-filter: blur(50px);
                -webkit-backdrop-filter: blur(50px);
                background-color: rgba(0, 0, 0, 0.9); /* Slightly darker for contrast */
            }
        `;
        document.head.appendChild(style);
    }
    
    async syncCurrentFile() {
        const file = this.app.workspace.getActiveFile();
        if (file) {
            await this.syncFile(file);
            new obsidian.Notice("Alias property synced!");
        }
    }
    
    async syncAllMarkdownFiles() {
        const files = this.app.vault.getMarkdownFiles();
        this.processBatchSync(files, "Syncing all files...");
    }

    async syncSelectedFolders(folders) {
        const filesToSync = new Set();
        const allMarkdownFiles = this.app.vault.getMarkdownFiles();

        allMarkdownFiles.forEach(file => {
            for (const folder of folders) {
                const folderPath = (folder.path === '/') ? '' : folder.path;
                
                if (folder.path === '/' && (!file.parent || file.parent.path === '/')) {
                     filesToSync.add(file);
                     break;
                }
                else if (folder.path !== '/' && file.path.startsWith(folderPath + '/')) {
                    filesToSync.add(file);
                    break;
                }
            }
        });
        
        if (filesToSync.size === 0) {
            new obsidian.Notice("No markdown files found in selected folders.");
            return;
        }

        await this.processBatchSync(Array.from(filesToSync), `Syncing ${filesToSync.size} files...`);
    }

    async processBatchSync(files, startMessage) {
        if (files.length === 0) return;
        
        new obsidian.Notice(startMessage);
        this.log(startMessage);
        
        let syncedCount = 0;
        for (const file of files) {
            if (this.app.vault.getAbstractFileByPath(file.path)) {
                 await this.syncFile(file, true); 
                 syncedCount++;
            }
        }
        
        new obsidian.Notice(`Completed! Synced aliases for ${syncedCount} files.`);
        this.log(`Batch sync finished. Total: ${syncedCount}`);
    }

    async removeAllAutoAliases() {
        const files = this.app.vault.getMarkdownFiles();
        if (files.length === 0) return;
        if (this.autoAliasLog.size === 0) {
            new obsidian.Notice("Log is empty. No aliases to remove.");
            return;
        }

        new obsidian.Notice(`Removing plugin aliases from ${files.length} files...`);
        let processedFiles = 0;
        
        for (const file of files) {
            if (this.app.vault.getAbstractFileByPath(file.path)) {
                await this.app.fileManager.processFrontMatter(file, (fm) => {
                    let existingAliases = [];
                    if (fm.aliases) existingAliases = Array.isArray(fm.aliases) ? fm.aliases : [fm.aliases];
                    else if (fm.alias) existingAliases = Array.isArray(fm.alias) ? fm.alias : [fm.alias];
                    
                    if (existingAliases.length === 0) return;

                    const userAliasesToKeep = existingAliases.filter(alias => 
                        !this.autoAliasLog.has(`${file.path}:${alias}`)
                    );

                    if (userAliasesToKeep.length > 0) {
                        fm.aliases = userAliasesToKeep;
                        delete fm.alias;
                    } else {
                        delete fm.aliases;
                        delete fm.alias;
                    }

                    existingAliases.forEach(alias => {
                        if (this.autoAliasLog.has(`${file.path}:${alias}`)) {
                            this.autoAliasLog.delete(`${file.path}:${alias}`);
                        }
                    });
                });
                await this.saveSettings();
                processedFiles++;
            }
        }
        new obsidian.Notice(`Cleanup complete. Processed ${processedFiles} files.`);
    }
    
    async syncFile(file, silent = false) {
        if (file.extension !== 'md') return;
        try {
            const content = await this.app.vault.read(file);
            const headings = this.extractHeadings(content);
            if (headings.length > 0 || this.isAliasPropertyPresent(file)) {
                await this.updateAliasProperty(file, content, headings);
                if (!silent) this.log(`Synced ${file.basename}`);
            }
        } catch (error) {
            this.log("Error syncing file:", error);
        }
    }

    isAliasPropertyPresent(file) {
        const cache = this.app.metadataCache.getFileCache(file);
        return cache && cache.frontmatter && (cache.frontmatter.aliases || cache.frontmatter.alias);
    }
    
    extractHeadings(content) {
        const levels = this.parseHeadingLevels(this.settings.headingsToTrack);
        const headingRegex = /^(#{1,6})\s+(.+)$/gm;
        const headings = [];
        const contentWithoutCodeBlocks = content.replace(/```[\s\S]*?```/g, ''); 
        let match;
        while ((match = headingRegex.exec(contentWithoutCodeBlocks)) !== null) {
            if (levels.includes(match[1].length)) headings.push(match[2].trim());
        }
        return headings;
    }
    
    parseHeadingLevels(setting) {
        const parts = setting.split("-");
        if (parts.length === 2) {
            const start = parseInt(parts[0]);
            const end = parseInt(parts[1]);
            if (!isNaN(start) && !isNaN(end) && start >= 1 && end <= 6 && start <= end) {
                return Array.from({ length: end - start + 1 }, (_, i) => start + i);
            }
        }
        return [1, 2, 3, 4, 5];
    }
    
    async updateAliasProperty(file, content, headings) {
        await this.app.fileManager.processFrontMatter(file, (fm) => {
            let existingAliases = [];
            if (fm.aliases) existingAliases = Array.isArray(fm.aliases) ? fm.aliases : [fm.aliases];
            else if (fm.alias) existingAliases = Array.isArray(fm.alias) ? fm.alias : [fm.alias];
            
            const userAliases = existingAliases.filter(alias => 
                !this.autoAliasLog.has(`${file.path}:${alias}`)
            );
            
            for (const entry of this.autoAliasLog) {
                if (entry.startsWith(`${file.path}:`)) this.autoAliasLog.delete(entry);
            }
            
            headings.forEach(h => this.autoAliasLog.add(`${file.path}:${h}`));
            
            const allAliases = [...new Set([...userAliases, ...headings])];
            if (allAliases.length > 0) {
                fm.aliases = allAliases;
                delete fm.alias; 
            } else if (!userAliases.length) {
                delete fm.aliases;
                delete fm.alias;
            }
        });
        await this.saveSettings();
    }
    
    async loadSettings() {
        const loadedData = await this.loadData();
        this.settings = Object.assign({}, DEFAULT_SETTINGS, loadedData);
        this.autoAliasLog = new Set(this.settings.autoAliasLogArray); 
    }
    
    async saveSettings() {
        this.settings.autoAliasLogArray = Array.from(this.autoAliasLog); 
        await this.saveData(this.settings);
    }
};

var AliasSettingTab = class extends obsidian.PluginSettingTab {
    constructor(app, plugin) {
        super(app, plugin);
        this.plugin = plugin;
    }
    
    display() {
        const { containerEl } = this;
        containerEl.empty();
        containerEl.createEl("h2", { text: "Alias Property Settings" });
        
        new obsidian.Setting(containerEl)
            .setName("Heading levels to track")
            .setDesc('Range 1-6 (e.g. "1-5")')
            .addText(text => text
                .setPlaceholder("1-5")
                .setValue(this.plugin.settings.headingsToTrack)
                .onChange(async (value) => {
                    this.plugin.settings.headingsToTrack = value || "1-5";
                    await this.plugin.saveSettings();
                }));
        
        new obsidian.Setting(containerEl)
            .setName("Sync on File Open")
            .setDesc("Automatically sync aliases when you open a file.")
            .addToggle(toggle => toggle
                .setValue(this.plugin.settings.syncOnFileOpen)
                .onChange(async (value) => {
                    this.plugin.settings.syncOnFileOpen = value;
                    await this.plugin.saveSettings();
                }));

        new obsidian.Setting(containerEl)
            .setName("Sync on Enter key")
            .setDesc("Automatically sync aliases when you press Enter.")
            .addToggle(toggle => toggle
                .setValue(this.plugin.settings.syncOnEnter)
                .onChange(async (value) => {
                    this.plugin.settings.syncOnEnter = value;
                    await this.plugin.saveSettings();
                }));
        
        new obsidian.Setting(containerEl)
            .setName("Enable logging")
            .addToggle(toggle => toggle
                .setValue(this.plugin.settings.enableLogging)
                .onChange(async (value) => {
                    this.plugin.settings.enableLogging = value;
                    await this.plugin.saveSettings();
                }));
    }
};

module.exports = AliasPropertyPlugin;